export const ADMIN_REQUEST: string = "ADMIN_REQUEST";
export const ADMIN_FAILURE: string = "ADMIN_FAILURE";
export const ADMIN_SUCCESS: string = "ADMIN_SUCCESS";
export const ADMIN_GET_PRODUCTS_SUCCESS: string = "ADMIN_GET_PRODUCTS_SUCCESS";
export const ADMIN_EDIT_PRODUCTS_SUCCESS: string = "ADMIN_EDIT_PRODUCTS_SUCCESS";
export const ADMIN_DELETE_PRODUCTS_SUCCESS: string = "ADMIN_DELETE_PRODUCTS_SUCCESS";
