import React from "react";
import { Footer } from "../Components/Footer";
import Navbar from "../Components/Navbar";

const Home = () => {
  return <div>
    <Navbar/>
    <h1>Home1</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <Footer/>
  </div>;
};
export default Home